Object.defineProperty(exports, "__esModule", {
    value: !0
}), exports.default = void 0;

var t, e = {
    baseUrl: t = "https://12580.fyzhgd.com/ApiGeteway/hehai_mg_6",
    getOpenId: "".concat(t, "/cApi/university/wechatApplet/jsCode2session/:jsCode"),
    getToken: "POST ".concat(t, "/cApi/login/sysLogin/token/:openId"),
    bindUser: "POST ".concat(t, "/cApi/university/wechatApplet/bindCampusCard"),
    bindStudent: "POST ".concat(t, "/cApi/university/wechatApplet/bindOpenId"),
    bindQiTa: "POST ".concat(t, "/cApi/visitor/bcyy/BindOpenId"),
    getUserInfo: "".concat(t, "/cApi/university/wechatApplet/getTeacherByOpenid"),
    getCode: "POST ".concat(t, "/cApi/university/wechatApplet/getValidCode"),
    updateUserSex: "POST ".concat(t, "/cApi/bathhouse/apply/updateSexByIdCard/:idCard/:sextype"),
    submitXSShenQing: "PUT ".concat(t, "/cApi/university-student-organ/stuentOutApply"),
    getXSShenHeJiLu: "".concat(t, "/cApi/university-student-organ/getStudentOutVerifierRecord1"),
    getXSShenHeList: "".concat(t, "/cApi/visitor/university-visitor-item/getStudentOutVerifierList"),
    updateMoreXSState: "PUT ".concat(t, "/cApi/visitor/university-visitor-user/auditor"),
    getXSAreaJiLu: "".concat(t, "/cApi/university/accessRecords/getCampusSiteRecords"),
    getXSMGJiLu: "".concat(t, "/cApi/university/accessRecords/getRecordsUnit"),
    submitShenQing: "POST ".concat(t, "/cApi/visitor/university-visitor-user/addVisitor"),
    getShenHeJiLu: "".concat(t, "/cApi/university/wechatApplet/listAuditorSafe"),
    getJiLuDetail: "".concat(t, "/cApi/university/wechatApplet/listAuditorSafeItem"),
    getAuditList: "".concat(t, "/cApi/university/wechatApplet/listAuditor"),
    updateAuditState: "PUT ".concat(t, "/cApi/university/wechatApplet/auditor/:openid/:visitorId/:state"),
    updateMoreAuditState: "PUT ".concat(t, "/cApi/visitor/university-visitor-user/auditor"),
    getTXInfo: "POST ".concat(t, "/cApi/visitor/university-gate/GateIdCard/:idCard/:id"),
    getTXInfoFromOther: "POST ".concat(t, "/cApi/university/wechatApplet/add"),
    getTXBath: "POST ".concat(t, "/cApi/bathhouse/apply/accessBathhouseByQRcode/:bathhouseId/:idCard"),
    getTXBus: "POST ".concat(t, "/cApi/visitor/bcyy/schoolBusCheck"),
    getTXBind: "POST ".concat(t, "/cApi/visitor/bcyy/BindOpenId"),
    getBusRecord: "".concat(t, "/cApi/visitor/bcyy/getCodeScanningRecords"),
    getUserList: "".concat(t, "/cApi/university/wechatApplet/getBatch"),
    getBlackList: "".concat(t, "/cApi/university/wechatApplet/listBlack"),
    getShenHeBlackList: "".concat(t, "/cApi/university/wechatApplet/listBlackToBeConfirmed"),
    shenhe1blackList: "POST ".concat(t, "/cApi/university/black/oneAuditBlack"),
    shenhe2blackList: "POST ".concat(t, "/cApi/university/black/twoAuditBlack"),
    shenhe1whiteList: "POST ".concat(t, "/cApi/university/black/oneAuditWhite"),
    shenhe2whiteList: "POST ".concat(t, "/cApi/university/black/twoAuditWhite"),
    updateUserDetail: "PUT ".concat(t, "/cApi/university/teacher-base/updateTeacher/:id"),
    deleteUser: "DELETE ".concat(t, "/cApi/university/teacher-base/deleteTeacher/:id"),
    addUser: "POST ".concat(t, "/cApi/university/teacher-base/addTeacher"),
    unbindUser: "".concat(t, "/cApi/university/wechatApplet/unBindUniversityTeacherOpenId"),
    getZaoTangList: "".concat(t, "/cApi/bathhouse/bathhouse/bathHouseListByName"),
    getZaoTangTimeList: "".concat(t, "/cApi/bathhouse/apply/selectDertailList"),
    submitZaoTangYuYue: "POST ".concat(t, "/cApi/bathhouse/apply/applyBathHouse"),
    getZaoTangSetting: "".concat(t, "/cApi/bathhouse/detail/selectBathHousetask/:id"),
    addNewZaoTangTime: "PUT ".concat(t, "/cApi/bathhouse/detail/addBathHousedetail"),
    getSelfZaoTangRecord: "".concat(t, "/cApi/bathhouse/apply/selectUserApplyList/:id"),
    cancelZaoTangYuYue: "PUT ".concat(t, "/cApi/bathhouse/apply/updateUserApply"),
    getAllRecord: "".concat(t, "/cApi/bathhouse/apply/ApplyListByDateAndName"),
    destoryZaoTangSetting: "POST ".concat(t, "/cApi/bathhouse/detail/updatetask"),
    getConfigSelectList: "".concat(t, "/cApi/bathhouse/detail/bathHouseListDR"),
    batchDetail: "POST ".concat(t, "/cApi/bathhouse/detail/updatedetailpl"),
    updateDetail: "POST ".concat(t, "/cApi/bathhouse/detail/updateBathHousedetail/:id"),
    deleteDetail: "DELETE ".concat(t, "/cApi/bathhouse/detail/deleteBathHousedetail/:id"),
    artificialConfirm: "POST ".concat(t, "/cApi/bathhouse/apply/QRCodeManualBathhouse/:bathhouseId/:applyUserId/:state"),
    addFamily: "POST ".concat(t, "/cApi/teacherFamily/addFamily"),
    getFamilyList: "".concat(t, "/cApi/teacherFamily/selectFamily"),
    updateFamily: "PUT ".concat(t, "/cApi/teacherFamily/updateFamily/:id"),
    deleteFamily: "DELETE ".concat(t, "/cApi/teacherFamily/deleteFamily/:id"),
    addFamilyShenHe: "POST ".concat(t, "/cApi/teacher-family-auditee/auditeeFamily"),
    getShenheList: "".concat(t, "/cApi/teacher-family-auditee/selectFamilyAuditee"),
    shenHeFamily: "PUT ".concat(t, "/cApi/teacher-family-auditee/updateAuditee"),
    getStepsData: "POST ".concat(t, "/cApi/sport-step/stepData"),
    getStepsList: "".concat(t, "/cApi/sport-step/getSportStepList"),
    getScoreList: "".concat(t, "/cApi/sport-step/selectSportStepScore"),
    updateSteps: "PUT ".concat(t, "/cApi/sport-step/updatAddress"),
    getScoreSetting: "".concat(t, "/cApi/sport-step/getSportStepScore"),
    getLeaderList: "".concat(t, "/cApi/university/wechatApplet/getOneTeacherBaseList"),
    applysportStep: "POST ".concat(t, "/cApi/sport-step/applysportStep")
};

exports.default = e;